### ISSUE TITLE
module 'hnswlib' has no attribute 'Index'

### ISSUE THREAD

**Issue by anna-pol** [nmslib/hnswlib#181] opened 2019-12-22 22:07 UTC
I downloaded hnswlib package to my env but I am constantly getting an error about 
AttributeError                            Traceback (most recent call last)
<ipython-input-82-d7ca02f5c196> in <module>
      1 # Declaring index
----> 2 p = hnswlib.Index(space = 'cosine', dim = EMBEDDING_SIZE) # possible options are l2, cosine or ip

AttributeError: module 'hnswlib' has no attribute 'Index'

**Comment by yurymalkov** [comment] 2019-12-23 03:05
Hi @anna-pol 
Did you try installing it via pip?

**Comment by anna-pol** [comment] 2019-12-23 09:16
@yurymalkov Yes, it installed the empty package with no methods.

**Comment by yurymalkov** [comment] 2019-12-23 15:41
@anna-pol Got it. Can you please provide the output of `pip install hnwlib`?

**Comment by anna-pol** [comment] 2019-12-23 16:06
![pic - Jupyter Notebook - Google Chrome 2019-12-23  (2)](https://user-images.githubusercontent.com/44748521/71367873-94d4e300-25a6-11ea-883f-c7abb6b2b3ab.png)
![ubuntu@Tupac_ _opt_visual 2019-12-23 16 49 48 (1)](https://user-images.githubusercontent.com/44748521/71367874-94d4e300-25a6-11ea-89b4-93ad36037f80.png)

**Comment by yurymalkov** [comment] 2019-12-23 18:00
Hm... Can you try using a different environment?
This issue is similar to #86 and #111.

**Comment by anna-pol** [comment] 2019-12-23 19:02
Yes,I did. The same issue even with different envs:/

**Comment by anna-pol** [comment] 2019-12-23 19:03
I looked at those issues it didn't help much.

**Comment by yurymalkov** [comment] 2019-12-23 22:34
Did you try creating a new environment in anaconda?

**Comment by anna-pol** [comment] 2019-12-24 10:04
Yes, the same downloading with no methods.

**Comment by yurymalkov** [comment] 2019-12-25 06:43
Cannot reproduce it. What is your platform?

**Comment by anna-pol** [comment] 2020-01-01 16:06
Linux, I set up anaconda env

**Comment by anna-pol** [comment] 2020-01-01 16:07
Is there any other possible solutions how can I launch it?

**Comment by yurymalkov** [comment] 2020-01-01 18:56
@anna-pol You can try clone the repository and do `python setup.py install` from a `python_bindings` folder in a clean python enviroment (with `pybind11`).

**Comment by anna-pol** [comment] 2020-01-01 21:31
Same issue. I tried few times. Are there any athor ways to declare Index?

**Comment by yurymalkov** [comment] 2020-01-01 23:48
@anna-pol This is some problem with your installation, not with the method of making and index.

One other thing that can cause it is that you have `hnswlib` folder somewhere in `$PATH` folders, so the script can import something else instead of the library.

**Comment by anna-pol** [comment] 2020-01-03 14:36
@yurymalkov thanks. The issue was solved. You were right the issue was with library paths.

**Comment by yurymalkov** [comment] 2020-01-03 20:17
@anna-pol glad to hear! Closing the issue

**Closed by yurymalkov** 2020-01-03 20:17 UTC

**Comment by guoyihonggyh** [comment] 2020-11-16 09:03
> @yurymalkov thanks. The issue was solved. You were right the issue was with library paths.
How to solve the library? I encounter the same problem as you do.
